### ISSUE TITLE
COVID-19 Data Hub Import Failure

### ISSUE THREAD

**Issue by eguidotti** [M3IT/COVID-19_Data#1]
Hello Matt,
I noticed that you are updating the structure of the repo.
This caused the import to the data hub to fail.
I'm now fixing the import. Can I rely on [this file](https://github.com/M3IT/COVID-19_Data/blob/master/Data/COVID_Data_Hub.csv)? Or should I consider also [the file for states](https://github.com/M3IT/COVID-19_Data/blob/master/Data/COVID_Data_Hub_State.csv)?
Many thanks
-- Emanuele

**Comment by M3IT** [comment]
Hi Emanuele,
Sorry about that, I made a code change that shouldn't have affected the file format and missed an error.  
The new file "COVID_Data_Hub.csv" was just a copy of the old one and I was going to do a pull at some point to change it.  I've fixed the coding issue, but will leave the file you're using now (COVID_Data_Hub.csv) with the incorrect headers and add a new file (COVID19_Data_Hub.csv) with corrected headers. I'll make a pull request to change to this new name and remove the colnames fix. I'll keep both files updated so you can merge the change whenever you're able.
Matt

**Comment by eguidotti** [comment]
Thank you very much for the quick fix.
I merged the pull request and everything seems to work fine again.
The file `COVID_Data_Hub.csv` is no longer needed.
Thanks again,
Emanuele
