### ISSUE TITLE
Incorrect data in the CSV file 

### ISSUE THREAD

**Issue by smi1eyDan** [M3IT/COVID-19_Data#11]
Hi,
Could I ask you to double check the data in the https://raw.githubusercontent.com/M3IT/COVID-19_Data/master/Data/COVID_AU_state.csv
When I look at the date range 29th Jan - 4th Feb it shows a second spike on Covid Confirmed cases which is not consistent with data from [Ourworldindata.org](https://ourworldindata.org/explorers/coronavirus-data-explorer?time=2022-01-02..latest&facet=none&pickerSort=desc&pickerMetric=location&Metric=Confirmed+cases&Interval=7-day+rolling+average&Relative+to+Population=true&Color+by+test+positivity=false&country=~AUS)
It also does not align with https://www.covid19data.com.au/states-and-territories

Many thanks
Dan

**Comment by M3IT** [comment]
Hi Dan, thanks for getting in touch.

In late January, some states started adding RAT results _en masse_ to the case count. e.g. Victoria added around 250k cases on 30 Jan, which accounts for a large spike. You can see this in the chart [here](https://infogram.com/covid-19-diagnoses-in-australian-states-and-territories-over-time-1gk92evl9on7p16?live) and the data download available on that page.  It's also visible in the Cumulative view of confirmed cases of COVID-19 in Australia chart on https://www.covid19data.com.au/states-and-territories - which shows that the 30 Jan spike contributes to the total Australian case count of 2.4 million, compared with OurWorldInData's total of 2.7m - I don't know their data sources, so can't account for the difference, but without the RAT test additions, it'd be even greater.

The files that are the source of the data for both this repo and https://www.covid19data.com.au have recently added separate columns for PCR test confirmed cases and RAT cases. It appears that covid19data.com.au uses only the PCR cases in some charts, but here I currently only use the combined figure - though plan to split them out at some point.

If you haven't already, it's also worth reading the [Data Notes](https://www.covid19data.com.au/data-notes).

If you have any further specific questions (e.g. changes on certain dates), please let me know.

**Comment by smi1eyDan** [comment]
Thanks Matt,
That makes sense I will need to normalize the data for Victoria  though, as it makes it look like a another spike. 
Thanks

**Comment by smi1eyDan** [comment]
Thanks for your detailed response.

Dan
