### ISSUE TITLE
GPL-3.0 License

### ISSUE THREAD

**Issue by georgberecz** [M3IT/COVID-19_Data#2]
Hello @M3IT,

Thanks a lot for putting in the work and providing these datasets publicly. Much appreciated! :)

I would love to use these datasets to integrate them into a global dataset, but unfortunately the GPL-3.0 stated in this repository prevents me from doing so, since it is incompatible with several other open licenses. For example, the US datasets from https://covidtracking.com/ are released under the Creative Commons CC BY-NC-4.0 and, therefore, not compatible.

Would you consider changing the license to something more permissive to allow for these use cases? E.g., the Creative Commons Attribution 4.0 International License that is also used on https://www.covid19data.com.au/ ?

Best,
Georg

**Comment by M3IT** [comment]
Thanks for bringing this to my attention George, I'd just used a default licence, which wasn't the best choice for this use case. I've updated it to CC BY 4.0.
If you're putting together a global dataset, are you aware of https://covid19datahub.io/ ?  This data feeds into that source, which has a dataset with global coverage.

**Comment by georgberecz** [comment]
Thanks a lot Matt! Much appreciated. Also, thanks a lot for pointing me to https://covid19datahub.io/. I was not aware of this project yet and will definitely check it out.
