### ISSUE TITLE
Vaccination data

### ISSUE THREAD

**Issue by jdbell92** [M3IT/COVID-19_Data#5]
Hey Matt,

Just noticed that the values for vaccines administered hasn't been updating since 16/6. Was just wondering if this was an issue or a decision to stop including those figures.

Thanks, Jake

**Comment by jennywlANU** [comment]
Hi  Matt,

I also have the same question as Jake as to why the vaccines figures haven't been updated since 16/6. I am looking for data related to vaccines and the manufacturer. 
Thanks in advance.
Regards,

Jenny
