### ISSUE TITLE
Vaccination data 

### ISSUE THREAD

**Issue by eguidotti** [M3IT/COVID-19_Data#6]
Hi Matt, 
I have been reading issue #5. I was wondering whether you'd be able to add two columns `vaccines_1` and `vaccines_2` in the data hub file: https://github.com/M3IT/COVID-19_Data/blob/master/Data/COVID19_Data_Hub.csv

I'm working on an update of the hub to include counts for the first as second dose. 
Thanks for your awesome collaboration on this project!

**Comment by M3IT** [comment]
Hi Emanuele, 
I've created a new file https://github.com/M3IT/COVID-19_Data/blob/master/Data/COVID19_Data_Hub_vacc_2.csv
Please review and if OK let me know when you'd like me to replace the existing file in the daily update.

**Comment by eguidotti** [comment]
Thanks for your quick response! Can you also keep the column `vaccines` with the total number of doses administrated? In some countries we already have 3 doses so I'm planning to keep:

- `vaccines`: total doses administrated
- `vaccines_1`: number of first doses
- `vaccines_2`: number of second doses

Everything else works perfectly.

**Comment by M3IT** [comment]
Amended as requested. Do you want this new file (COVID19_Data_Hub_vacc_2.csv) replacing the current one (COVID19_Data_Hub.csv) immediately?
Note also that there's a slight discrepancy for recent weeks where vaccines != vaccines_1 + vaccines_2. I'm looking into this at the data source.

**Comment by eguidotti** [comment]
> Amended as requested. Do you want this new file (COVID19_Data_Hub_vacc_2.csv) replacing the current one (COVID19_Data_Hub.csv) immediately?

Yes please! 

> Note also that there's a slight discrepancy for recent weeks where vaccines != vaccines_1 + vaccines_2. I'm looking into this at the data source.

No surprise, that's why I'd like to keep all the three columns :) It could be for third doses, missing counts, errors in reporting... `vaccines` should be independent from `vaccines_1` and `vaccines_2`

**Comment by M3IT** [comment]
Done

**Comment by eguidotti** [comment]
Thanks!
